// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYG6DNX3F99xKUrIUA8ndYtkvKWWNDP4s',
    appId: '1:381008282202:web:a2cc1b19e5cbc96f534e63',
    messagingSenderId: '381008282202',
    projectId: 'sharfianshospital-c2a4e',
    authDomain: 'sharfianshospital-c2a4e.firebaseapp.com',
    storageBucket: 'sharfianshospital-c2a4e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUVqiFYEYdER3FTXpGuEXkGzOwwpqPEA0',
    appId: '1:381008282202:ios:f9c1647efd6a714e534e63',
    messagingSenderId: '381008282202',
    projectId: 'sharfianshospital-c2a4e',
    storageBucket: 'sharfianshospital-c2a4e.firebasestorage.app',
    iosBundleId: 'com.sharfianshospital.sharfianApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYG6DNX3F99xKUrIUA8ndYtkvKWWNDP4s',
    appId: '1:381008282202:web:1b80d800db124f0b534e63',
    messagingSenderId: '381008282202',
    projectId: 'sharfianshospital-c2a4e',
    authDomain: 'sharfianshospital-c2a4e.firebaseapp.com',
    storageBucket: 'sharfianshospital-c2a4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVqiFYEYdER3FTXpGuEXkGzOwwpqPEA0',
    appId: '1:381008282202:ios:f9c1647efd6a714e534e63',
    messagingSenderId: '381008282202',
    projectId: 'sharfianshospital-c2a4e',
    storageBucket: 'sharfianshospital-c2a4e.firebasestorage.app',
    iosBundleId: 'com.sharfianshospital.sharfianApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1cTZXNQMlG_kBsHr3VhyydjxlJ7Bhvgc',
    appId: '1:381008282202:android:b2fdeac9d1529d61534e63',
    messagingSenderId: '381008282202',
    projectId: 'sharfianshospital-c2a4e',
    storageBucket: 'sharfianshospital-c2a4e.firebasestorage.app',
  );
}
